# Generated by Django 4.2.3 on 2023-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_num', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('height_feet', models.PositiveIntegerField()),
                ('height_inches', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
