# Generated by Django 4.2.3 on 2023-09-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(default=171, max_length=20),
            preserve_default=False,
        ),
    ]
