# Generated by Django 4.2.3 on 2023-09-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_remove_player_age_player_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='dob',
            new_name='born',
        ),
    ]
