# Generated by Django 4.2.3 on 2023-09-13 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '0003_rename_dob_player_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_num',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=3),
        ),
    ]
