# Generated by Django 4.2.3 on 2023-09-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_player_user_id_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
    ]
